development:
  server: localhost
  path: /solr/jobs
  port: 8983

test:
  server: localhost
  path: /solr/jobs
  port: 8983

production:
  server: production-support-backend
  path: /solr/jobs
  port: 8983